app:
  datasource:
    jdbc-url: jdbc:postgresql://35.247.158.10:5432/demodb
    username: aceit
    password: ntucz2006
    pool-size: 30

  cloud:
    gcp:
      sql:
        instance-connection-name: aerobic-pivot-270810:asia-southeast1:event-sg-db
        database-name: demodb

# local host database
# jdbc-url: jdbc:postgresql://localhost:5432/demodb