app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password
    pool-size: 30


# local host database
# jdbc-url: jdbc:postgresql://localhost:5432/demodb

